name: isbn-verifier
version: 2.7.0.9

dependencies:
  - base

library:
  exposed-modules: IsbnVerifier
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - MissingH

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - isbn-verifier
      - hspec
